#!/usr/bin/env python
import os
import subprocess
import sys

from definitions import nl
from pack.modules.core.config_mgmt.environment_checks import monk_env_checks
from pack.modules.core.config_mgmt.regen_config_env_defs import regenerate_config_env_defs
from pack.modules.core.theme.theme_functions import print_t
from pack.modules.core.utils.find_entity import find_entity
from pack.modules.core.utils.monk_helpers.handle_alternate_actions import handle_alternate_actions
from pack.modules.core.utils.monk_helpers.handle_special_commands import handle_special_commands
from pack.modules.core.utils.monk_helpers.parse_monk_args import parse_monk_args
from pack.modules.core.utils.monk_helpers.run_command_as_module import run_command_as_module

# Some basic environment checks
monk_env_checks()

# Regenerate "magic" config/env stuff
regenerate_config_env_defs()

# Setup and Parse Monk Arguments
args, unknown_args, action, entity, entity_type = parse_monk_args()

# Special Commands that override typical behavior (reasoning in definition)
if handle_special_commands(args, action, entity, entity_type):
    sys.exit(0)

# Find Entity (includes interactive selection)
entity_path = find_entity(entity, entity_type)

# Handle Alternate Actions (edit, print, copy_path, help, etc)
if handle_alternate_actions(action, entity_path):
    sys.exit(0)

# Get the extension of the script
extension = os.path.splitext(entity_path.strip())[1]

# Run the script with the provided arguments
if extension == ".sh":
    subprocess.call(['bash', entity_path.strip()] + sys.argv[2:])
elif extension == ".bat":
    subprocess.call([entity_path.strip()] + sys.argv[2:])
elif extension == ".py":
    try:
        # args = vars(args)
        run_command_as_module(entity_path.strip(), 'main', args)
    except KeyboardInterrupt:
        print_t(f"{nl}Exiting due to KeyboardInterrupt from user.", 'quiet')
        sys.exit(1)
else:
    print_t(f"Entity Type not supported: {extension}. find_entity.py should have filtered this out.", 'error')
    sys.exit(1)
