# Monkey Config Defaults
#
# This file is used to set default values for monkey configs.
# It is also the source of truth for all monkey config options, so if you add or alter
# something here, it is written to the MonkeyConfig class and .env.default.
# (you must update .env manually)

# RULES
# - Keys must be SNAKE_CASE
# - Keys with a word-boundaried "PATH" are validated as PATH
# - Keys with a word-boundaried "PROMPT" are validated as PROMPT
# - Keys with a word-boundaried "MODEL" are validated as MODEL
# - Keys with a word-boundaried "TEMP" are validated as TEMP
# - Other keys are validated as primitives (str, bool, etc)
#
#   PATH values will replace 'ROOT_PATH' with your project's root path
#
# - Validation logic is defined in
#   `modules/source/config/monkey_config_validations.py`

# General
WORK_PATH: "ROOT_PATH/stor/work_path"
FILE_TYPES_INCLUDED: ".js,.vue,.php"
FILEPATH_MATCH_INCLUDE: null
FILEPATH_MATCH_EXCLUDE: ".config,.md,.git,migrations,vite,webpack,.txt"
FILE_SELECT_MAX_TOKENS: 7000
MAX_TOKENS: 8000


# Main Prompts
MAIN_PROMPT: "Please generate code for the following task..."
MAIN_PROMPT_ULTIMATUM: "Limit your response to the full contents of a python script, and nothing else."
OUTPUT_EXAMPLE_PROMPT: "Limit your output strictly to the contents of the file, like this: ```complete contents of file```."

# Context / Summary
# Note: Insert un-summarized context files into PROMPTs with {cop:<filepath>}
CONTEXT_FILE_PATH: "ROOT_PATH/stor/context/context-file.txt"
CONTEXT_SUMMARY_PROMPT: "Provide a summary of this file..."

# Output Checks
OUTPUT_CHECK_PROMPT: null
OUTPUT_TRIES: 1

# Output
OUTPUT_PATH: "ROOT_PATH/stor/output"
OUTPUT_EXT: ".py"
OUTPUT_FILENAME_APPEND: ""
OUTPUT_REMOVE_STRINGS: "```,```python"
SKIP_EXISTING_OUTPUT_FILES: True

# Editor
# Editor
EDITOR_PROMPT: null
EDITOR_PROMPT_ULTIMATUM: null

# Output Splitting
OUTPUT_SPLIT_PATH: null
OUTPUT_SPLIT_TAG: '[SPLIT]'

# Git Commit
COMMIT_STYLE: null # null, 'gpt', 'static'
STATIC_COMMIT_MESSAGE: 'File updated with CodeMonkeys'

# Models
MAIN_MODEL: 4
SUMMARY_MODEL: 4
OUTPUT_CHECK_MODEL: 3

# Temps
MAIN_TEMP: 1.0
SUMMARY_TEMP: 1.0
OUTPUT_CHECK_TEMP: .5
