name: Deploy Sphinx documentation to Pages

on:

  push:

    branches: [main] # branch to trigger deployment

jobs:

  pages:

    runs-on: ubuntu-20.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Print entire directory structure
        run: |
          ls -R /home/runner/work

      - id: deployment
        uses: sphinx-notes/pages@v3
